###
POST http://localhost:4400/api/favorite HTTP/1.1
Content-Type: application/json

{
    "link" : "cuchau"
}

###
GET http://localhost:4400/api/favorite HTTP/1.1
Content-Type: application/json

###
GET http://localhost:4400/api/favorite/62b1436f601bfa6acecde57d HTTP/1.1
Content-Type: application/json
 
###
PUT http://localhost:4400/api/favorite/62b145974102ad5a83cd780c HTTP/1.1
Content-Type: application/json

{
    "link" : "update"
}

###
DELETE http://localhost:4400/api/favorite/62b14966ee9cdd1b760a20d6 HTTP/1.1
Content-Type: application/json